# -*- coding: utf-8 -*-

from django.utils.translation import ugettext as _


WRITER_TYPE = _('writer')
ADMIN_TYPE = _('admin')

RESERVED_WORDS = (
    'about',
    'accounts',
    'activity',
    'admin',
    'api',
    'api-auth',
    'blog',
    'brand',
    'business',
    'careers',
    'checkout',
    'cities_light',
    'comment',
    'complete-signup',
    'confirmation',
    'contact',
    'courses',
    'credits',
    'edit',
    'enrollment',
    'enrollment-completed',
    'enrollment-toogle',
    'enrollment-uncompleted',
    'extra-signup',
    'follow',
    'forum',
    'free-goods',
    'giftcards',
    'grappelli',
    'guides',
    'hello',
    'hi',
    'home',
    'hub',
    'jobs',
    'l',
    'learn',
    'like',
    'live',
    'login',
    'logout',
    'media',
    'members',
    'membership',
    'notify',
    'org',
    'organization',
    'partner',
    'payments',
    'privacy',
    'profile',
    'project',
    'projects',
    'recover',
    'referrals',
    'settings',
    'signup',
    'staff',
    'static',
    'store',
    'subscribe',
    'teach',
    'team',
    'terms',
    'terms-of-use',
    'thanks',
    'toggle',
    'unfollow',
    'unlike',
    'user',
    'users',
    'validate-username-email',
    'welcome',
    'debug',
    'bundle',
)
